### ISSUE TITLE
Possible to include all minfi's cell type references in the meffil.estimate.cell.counts.from.betas function?

### ISSUE THREAD

**Issue by Lei-Guo** [perishky/meffil#24]
The current function only estimates cell types in blood/saliva. Could you please also include the brain (DLPFC) cell type reference (from minfi) in this function?

**Comment by perishky** [comment]
Hi Lei-Guo, 

Sorry about the wait.  I haven't been monitoring this closely enough.  I've recently added this, it is named "guintivano dlpfc".

Matt

**Comment by samuel-carleial** [comment]
Hi Matt,
to my understanding, this is one of the few, if not the only, function in R that can estimate cell counts for saliva samples specifically (besides GLINT perhaps?). I have a study in which I want to estimate cell counts from saliva samples. I noticed that in the abovementioned function there is the reference called "saliva gse48472". 

I assume this should not be used for both saliva and buccal cells, but only saliva, correct? 
Could you then give me more information on that cell-type reference, and whether there is a reference study/publication that report it?

I would appreciate it very much, because I am planing to use your function in my pipeline.
*Maybe one suggestion would be to add this information in the documentation of the package.

**Comment by perishky** [comment]
Hi Samuel,

This particular cell count reference is obtained by combining a white blood cell type reference (GEO dataset: GSE35069<https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE35069>) with a buccal cell type reference (the buccal DNA methylation profiles from GEO dataset GSE48472<https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE48472>).  It assumes that the cell content of saliva is a mix of white blood cells and buccal epithelial cells.

You could use this for either buccal samples or saliva samples.

Best,
Matt

________________________________

**Comment by samuel-carleial** [comment]
Hi Matt,
I found that out also inside your code. Thank you for the feedback!
