### ISSUE TITLE
How to make sure meffil matches the newly added EPIC b5 manifest 

### ISSUE THREAD

**Issue by ox852** [perishky/meffil#27]
Hi Perishky,

I am trying to add the EPIC b5 manifest (released in Mar 2020) to meffil and did the following:

In the `load-epic-manifest.r` script
1. update of `filename <- "ftp://webdata2:webdata2@ussd-ftp.illumina.com/downloads/productfiles/methylationEPIC/infinium-methylationepic-v-1-0-b5-manifest-file-csv.zip"`)
2. ## add snp exclusions (re issue #17 )
    `manifest$snp.exclude <- manifest$Name %in% with(manifest, Name[which(as.numeric(as.character(SNP_MinorAlleleFrequency)) > 0.01)])`

Then add EPIC annotation/updated manifest (ref. meffil/data-raw/globals.r) by sourcing the above script and use `load.epic.manifest()`, the following warning comes up (Is it okay to proceed?): 
```
In which(as.numeric(as.character(SNP_MinorAlleleFrequency)) > 0.01) :
  NAs introduced by coercion
```

After `meffil.add.chip("epic", manifest.epic)`, what else should be done to ensure meffil now is matching the meffil objects to the newly added manifest? Is it automatic? or any other steps to enforce it to work on meffil objects (something like `guess.chip()`)?

Thank you very much, as I couldn't find tutorial materials for this bit (if I overlook it, sorry for opening the question here; reference to the tutorial would be very much appreciated).

Thanks

**Comment by perishky** [comment]
I've updated the epic to the file you listed.  If you reinstall meffil, everything should be up to date.  I've also fixed issues #17.

There's no tutorial for updating the chip annotations. Here is what I did:

- updated the link to the new annotation file in in data-raw/load-epic-annotation.r
- started R with working directory in data-raw/
- ran the following code
library(devtools)
library(meffil)
source("load-epic-manifest.r")
manifest.epic <- load.epic.manifest()
meffil.add.chip("epic", manifest.epic)
meffil:::save.globals("../inst") ## this saves the new annotation to your R installation so that it is loaded by default next time you start R and load meffil  (otherwise you have run meffil.add.chip with the new annotation each time you start R and load meffil)
