### ISSUE TITLE
Normalize a subset of samples

### ISSUE THREAD

**Issue by yocra3** [perishky/meffil#31]
Good afternoon,

I am planning to use meffil to normalize my data. I do not have any problems to write the code, but I have doubts with the design.

When the methylation data was generated, samples from different cohorts were included in the same array. However, currently I am only interested in analyzing one cohort, so I would only like to analyze around a 10% of the total samples. 

In the manual, I have read that meffil uses functional normalization. What approach should be better in my case:

1. Normalize all the samples together and then select the samples I am interested in.
2. Select the samples I am interested in the sample sheet and only normalize my subset.

I have not been able to find information about this topic, either in the manual or in any article. Let me know if we can move this discussion to a more suitable place.

Thank you very much,

**Comment by perishky** [comment]
Sorry about the wait, thought I had responded.  If you want to adjust for slide effects, then you will need to normalize everything together (Option 1). This would be up to 'meffil.normalize.quantiles()' in the pipeline. You would then only need to apply 'meffil.normalize.samples()' the samples in your cohort because the data adjustments to applied are fully determined by the 'meffil.normalize.quantiles' function.  If you attempt Option 2, then attempting to adjust for slide effects then the normalization will actually fail because you will almost certainly have several cases where only one sample is included on a slide.   With Option 2, you could ignore slide effects, but in our experience they tend to have pretty strong effects on the data.  

Let me know if you have further questions.

**Comment by yocra3** [comment]
Thank you very much @perishky. I have tried both approaches and I got the best performance when normalizing everything together and the adjusting for a batch variable. I close the issue.
