### ISSUE TITLE
qc.objects - annotation

### ISSUE THREAD

**Issue by laurahf** [perishky/meffil#39]
Greetings. First of all, thank you for developing this useful package!
I'm new to using Meffil and I had been following the guidelines on the readme.md for step-by-step normalization when I ran into an issue.

I got to this part of the guidance:
#save the SNP names in R
annotation <- qc.objects[[1]]$annotation
writeLines(meffil.snp.names(annotation), con="snp-names.txt")

I couldn't get this code to run because my qc.objects dataset doesn't have a variable named annotation. Do you know why it might not have generated the annotation variable?

**Comment by perishky** [comment]
Ah, sorry, that was our mistake in the documentation.  The code should be written as follows:

featureset <- qc.objects[[1]]$featureset
writeLines(meffil.snp.names(featureset), con="snp-names.txt")

i.e. 'featureset' rather than 'annotation'. Thank you for pointing this out!

________________________________
From: laurahf ***@***.***>
Sent: 27 May 2022 6:29 PM
To: perishky/meffil ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [perishky/meffil] qc.objects - annotation (Issue #39)


Greetings. First of all, thank you for developing this useful package!
I'm new to using Meffil and I had been following the guidelines on the readme.md for step-by-step normalization when I ran into an issue.

I got to this part of the guidance:
#save the SNP names in R
annotation <- qc.objects[[1]]$annotation
writeLines(meffil.snp.names(annotation), con="snp-names.txt")

I couldn't get this code to run because my qc.objects dataset doesn't have a variable named annotation. Do you know why it might not have generated the annotation variable?

**Comment by epzjlm** [comment]
Hi Matt,

On the wiki in “sample QC” should we also update following line:

writeLines(meffil.snp.names(), con="snp-names.txt”)

BW,
Josine




On 30 May 2022, at 09:46, Matthew Suderman ***@***.******@***.***>> wrote:


Ah, sorry, that was our mistake in the documentation. The code should be written as follows:

featureset <- qc.objects[[1]]$featureset
writeLines(meffil.snp.names(featureset), con="snp-names.txt")

i.e. 'featureset' rather than 'annotation'. Thank you for pointing this out!

________________________________
From: laurahf ***@***.***>
Sent: 27 May 2022 6:29 PM
To: perishky/meffil ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [perishky/meffil] qc.objects - annotation (Issue #39)


Greetings. First of all, thank you for developing this useful package!
I'm new to using Meffil and I had been following the guidelines on the readme.md for step-by-step normalization when I ran into an issue.

I got to this part of the guidance:
#save the SNP names in R
annotation <- qc.objects[[1]]$annotation
writeLines(meffil.snp.names(annotation), con="snp-names.txt")

I couldn't get this code to run because my qc.objects dataset doesn't have a variable named annotation. Do you know why it might not have generated the annotation variable?
