### ISSUE TITLE
Guidance on plink step in QC

### ISSUE THREAD

**Issue by iskandari** [perishky/meffil#41]
First of all, thank you @perishky for open sourcing this very [well-documented](https://github.com/perishky/meffil/wiki/Sample-QC) methylation data analysis package.  For those of us new to biostatistics, could you briefly explain or elaborate on the QC step that involves `plink`?  Having gone through the [tutorial](https://zzz.bwh.harvard.edu/plink/tutorial.shtml), I am uncertain about where to obtain the binary .ped file `dataset` which is a required input to the `--bfile` argument (in addition to snp-names.txt, which we get from qc objects featureset).   I am working with [methylation data ](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE134379)from two different brain regions and am therefore using the `guintivano dlpfc` cell reference type.  So far, I have found [this tool](https://gist.github.com/CholoTook/60968e3ab6d90cb8fd19be55a25592f1) for converting GEO samples to .ped format using GSM accession ID, but am not sure which sample to use.  Any guidance about how/where to obtain the matrix of genotypes for comparison, or where to find out more about this process, would be helpful.  Thank you!

**Comment by neuromik** [comment]
Having the same issue. Where bfile dataset comes from?
plink --bfile dataset --extract snp-names.txt --recodeA --out genotypes.raw --noweb

**Comment by perishky** [comment]
Sorry about the wait, it's been a busy month but things are returning to normal. From what I understand, you'd like to verify that the genotypes measured in brain region A match the genotypes measured in brain region B for each study participant. This is a use-case that we don't fully support (yet!) but it is nevertheless possible:

## first split your QC objects by brain region
qc.objects.A <- ... ## i.e. qc objects for samples measured in brain region A
qc.objects.B <- ... ## i.e. qc objects for samples measured in brain region B
## ensure that qc.objects.A and qc.objects.B have study participants in same order
... ## dataset-specific, the samplesheet should provide the study participant IDs
## extract genotypes for brain region A samples
snp.betas.A <- meffil.snp.betas(qc.objects.A)
genotypes.A <- meffil:::calculate.beta.genotypes(snp.betas.A)
## make the sample names match for corresponding study participants (easy because qc objects were ordered by parcticipant)
colnames(genotypes.A) <- names(qc.objects.B)
## generate the summary for brain region B while verifying genotypes match region A
qc.summary.B <- meffil.qc.summary(qc.objects.B, genotypes.A)

I think that should work.  Do let me know how it goes. I'll do my best to respond in a timely manner to this issue.
